version: '3.8'
services:
  # GITLAB
  gitlab-web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: gitlab-web
    hostname: ${GITLAB_HOSTNAME}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_EXTERNAL_URL}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
        gitlab_rails['initial_root_password'] = '${GITLAB_ROOT_PASSWORD}'
        gitlab_rails['time_zone'] = '${GITLAB_TIME_ZONE}'
        gitlab_rails['gitlab_email_from'] = '${GITLAB_EMAIL_FROM}'
        gitlab_rails['smtp_enable'] = ${GITLAB_SMTP_ENABLE}
    ports:
      - "${GITLAB_HTTP_PORT}:80"
      - "${GITLAB_HTTPS_PORT}:443"
      - "${GITLAB_SSH_PORT}:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - gitlab-network

  # RUNNER
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    container_name: gitlab-runner
    hostname: ${GITLAB_RUNNER_HOSTNAME}
    environment:
      - REGISTRATION_TOKEN=${GITLAB_RUNNER_REGISTRATION_TOKEN}
    depends_on:
      - gitlab-web
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab-network

networks:
  gitlab-network:
    name: gitlab-network

volumes:
  gitlab_config:
    driver: local
    driver_opts:
      type: none
      device: ${GITLAB_DATA_PATH}/config
      o: bind
  gitlab_logs:
    driver: local
    driver_opts:
      type: none
      device: ${GITLAB_DATA_PATH}/logs
      o: bind
  gitlab_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: ${GITLAB_DATA_PATH}/data
    #   o: bind
  gitlab_runner_config:
    driver: local
    driver_opts:
      type: none
      device: ${GITLAB_DATA_PATH}/runner/config
      o: bind
